/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agencia_viajes;

/**
 *
 * @author Usuario
 */
public class PantallaPerfil extends javax.swing.JFrame {

    private int idCliente;

    public PantallaPerfil(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
        cargarPuntos();

        jButton1.addActionListener(e -> canjearPuntos());
        jButton2.addActionListener(e -> canjearPuntos());
        jButton3.addActionListener(e -> canjearPuntos());
        jToggleButton2.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Aplicar Promocion 20%");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 860, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aplicar Promocion 20%");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 860, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Aplicar Promocion 20%");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 860, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/TailandiaMini.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 720, 260, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/TokioMini.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 720, 260, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("COSTO -- 10.000 Puntos");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 670, 200, -1));

        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 290, 730, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/descarga.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 720, 260, -1));

        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setText("Notificaciones");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, 230, 30));

        jTextField3.setBackground(new java.awt.Color(102, 102, 255));
        jTextField3.setText("Metodo Pago");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 790, 230, 30));

        jTextField2.setBackground(new java.awt.Color(102, 102, 255));
        jTextField2.setText("Correo Electronico");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 230, 30));

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Nombre Usuario");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/ChatGPT Image 26 may 2026, 13_44_30 (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 960, 90, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canjearPuntos() {
        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(
                         "UPDATE Cliente SET record_juego = record_juego - 10000 " +
                         "WHERE idCliente = ? AND record_juego >= 10000")) {
                ps.setInt(1, idCliente);
                int filas = ps.executeUpdate();
                javax.swing.SwingUtilities.invokeLater(() -> {
                    if (filas == 1) {
                        int nuevos = Integer.parseInt(jLabel2.getText()) - 10000;
                        jLabel2.setText(String.valueOf(nuevos));
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "¡Promoción aplicada! Se han descontado 10.000 puntos.",
                            "Canje exitoso",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "No tienes suficientes puntos.\nNecesitas al menos 10.000 puntos.",
                            "Puntos insuficientes",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    }
                });
            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() ->
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al canjear puntos:\n" + ex.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE)
                );
            }
        });
    }

    private void cargarPuntos() {
        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(
                         "SELECT record_juego, nomUsuario, Email FROM Cliente WHERE idCliente = ?")) {
                ps.setInt(1, idCliente);
                try (java.sql.ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        int puntos = rs.getInt("record_juego");
                        String usuario = rs.getString("nomUsuario");
                        String email   = rs.getString("Email");
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jLabel2.setText(String.valueOf(puntos));
                            jTextField1.setText(usuario != null ? usuario : "");
                            jTextField2.setText(email   != null ? email   : "");
                        });
                    }
                }
            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() -> jLabel2.setText("0"));
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPerfil(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
