/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agencia_viajes;

/**
 *
 * @author Usuario
 */
public class PantallaRegistro extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRegistro
     */
    public PantallaRegistro() {
        initComponents();
        configurarPlaceholders();
        configurarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 230, 255), 3, true));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(228, 243, 241));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(222, 229, 227), 3, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(217, 224, 223));
        jTextField3.setForeground(new java.awt.Color(186, 181, 181));
        jTextField3.setText("NombreUsuario");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 210, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 183, 183));
        jLabel2.setText("Tu proxima aventura te esta esperando");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("SkyRouteJoruney");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(217, 224, 223));
        jTextField1.setForeground(new java.awt.Color(186, 181, 181));
        jTextField1.setText("Apellidos");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 210, 30));

        jTextField2.setBackground(new java.awt.Color(217, 226, 225));
        jTextField2.setForeground(new java.awt.Color(187, 183, 183));
        jTextField2.setText("Nombre");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, 30));

        jTextField4.setBackground(new java.awt.Color(217, 224, 223));
        jTextField4.setForeground(new java.awt.Color(186, 181, 181));
        jTextField4.setText("Email");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 210, 30));

        jTextField5.setBackground(new java.awt.Color(217, 224, 223));
        jTextField5.setForeground(new java.awt.Color(186, 181, 181));
        jTextField5.setText("Telefono");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 210, 30));

        jTextField6.setBackground(new java.awt.Color(217, 224, 223));
        jTextField6.setForeground(new java.awt.Color(186, 181, 181));
        jTextField6.setText("Contraseña");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 210, 30));

        jToggleButton3.setBackground(new java.awt.Color(0, 153, 153));
        jToggleButton3.setForeground(new java.awt.Color(204, 204, 255));
        jToggleButton3.setText("Registrar Cuenta");
        jToggleButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 255), 2, true));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        jToggleButton2.setBackground(new java.awt.Color(0, 155, 155));
        jToggleButton2.setForeground(new java.awt.Color(204, 204, 255));
        jToggleButton2.setText("Volver Inicio Sesion");
        jToggleButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(206, 206, 255), 2));
        jPanel3.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 370, 480));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/fondo_960x540.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 959, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        registrar();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void configurarPlaceholders() {
        java.awt.Color gris  = new java.awt.Color(186, 181, 181);
        java.awt.Color negro = new java.awt.Color(40, 40, 40);

        configurarCampo(jTextField2, "Nombre",        gris, negro);
        configurarCampo(jTextField1, "Apellidos",     gris, negro);
        configurarCampo(jTextField4, "Email",         gris, negro);
        configurarCampo(jTextField5, "Telefono",      gris, negro);
        configurarCampo(jTextField6, "Contraseña",    gris, negro);
        configurarCampo(jTextField3, "NombreUsuario", gris, negro);
    }

    private void configurarCampo(javax.swing.JTextField campo, String placeholder,
                                  java.awt.Color gris, java.awt.Color negro) {
        campo.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (campo.getText().equals(placeholder)) {
                    campo.setText("");
                    campo.setForeground(negro);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (campo.getText().isEmpty()) {
                    campo.setText(placeholder);
                    campo.setForeground(gris);
                }
            }
        });
    }

    private void configurarBotones() {
        // Volver al login sin registrar
        jToggleButton2.addActionListener(e -> {
            new PantallaIncio().setVisible(true);
            dispose();
        });
    }

    private boolean campoVacio(javax.swing.JTextField campo, String placeholder) {
        return campo.getText().trim().isEmpty() || campo.getText().trim().equals(placeholder);
    }

    private void registrar() {
        String nombre    = jTextField2.getText().trim();
        String apellidos = jTextField1.getText().trim();
        String email     = jTextField4.getText().trim();
        String telefono  = jTextField5.getText().trim();
        String contrasena = jTextField6.getText().trim();
        String nomUsuario = jTextField3.getText().trim();

        // Validar campos obligatorios
        if (campoVacio(jTextField2, "Nombre")     || campoVacio(jTextField1, "Apellidos") ||
            campoVacio(jTextField4, "Email")       || campoVacio(jTextField6, "Contraseña") ||
            campoVacio(jTextField3, "NombreUsuario")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor rellena todos los campos obligatorios\n(Nombre, Apellidos, Email, Contraseña y Usuario).",
                "Campos incompletos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            jToggleButton3.setSelected(false);
            return;
        }

        // Deshabilitar botón mientras se procesa
        jToggleButton3.setEnabled(false);
        jToggleButton3.setText("Registrando...");

        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.CallableStatement cs = con.prepareCall("{CALL sp_registrar_cliente(?, ?, ?, ?, ?, ?, ?, ?)}")) {

                cs.setString(1, nombre);
                cs.setString(2, apellidos);
                cs.setString(3, email);
                cs.setString(4, telefono.isEmpty() ? null : telefono);
                cs.setString(5, contrasena);
                cs.setString(6, nomUsuario);
                cs.registerOutParameter(7, java.sql.Types.INTEGER); // resultado
                cs.registerOutParameter(8, java.sql.Types.INTEGER); // idCliente

                cs.execute();

                int resultado = cs.getInt(7);

                javax.swing.SwingUtilities.invokeLater(() -> {
                    jToggleButton3.setEnabled(true);
                    jToggleButton3.setText("Registrar Cuenta");
                    jToggleButton3.setSelected(false);

                    if (resultado == 1) {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "¡Cuenta creada correctamente!\nYa puedes iniciar sesión con tu email y contraseña.",
                            "Registro exitoso",
                            javax.swing.JOptionPane.INFORMATION_MESSAGE);
                        new PantallaIncio().setVisible(true);
                        dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "El email introducido ya está registrado.",
                            "Email duplicado",
                            javax.swing.JOptionPane.WARNING_MESSAGE);
                    }
                });

            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jToggleButton3.setEnabled(true);
                    jToggleButton3.setText("Registrar Cuenta");
                    jToggleButton3.setSelected(false);
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Error de conexión con la base de datos:\n" + ex.getMessage(),
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                });
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
