/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agencia_viajes;

/**
 *
 * @author Usuario
 */
public class PantallaPlanificarViaje extends javax.swing.JFrame {

    private int idCliente;
    private int idDestinoSeleccionado = -1;
    private double precioBase       = 0;
    private double precioHotel      = 0;
    private double precioHabitacion = 0;
    private double precioActividades = 0;

    public PantallaPlanificarViaje(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
        configurarUI();
        cargarPrecioDestino();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox1.setFont(new java.awt.Font("Viner Hand ITC", 3, 36)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Roma", "Tokio", "Paris", "Dubai", "NuevaYork", "Londres", "Bali", "Tailandia", "Maldivas" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 326, 700, 70));

        jComboBox2.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cama Individual", "Cama Doble", "Cama Balcon", " " }));
        jComboBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, 500, 70));

        jComboBox3.setBackground(new java.awt.Color(102, 102, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Estrellas", "5 Estrellas" }));
        jComboBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 255), 2, true));
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 436, 530, 70));

        jTextField1.setBackground(new java.awt.Color(102, 102, 255));
        jTextField1.setText("Actividades");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 666, 490, 60));

        jTextField2.setBackground(new java.awt.Color(102, 102, 255));
        jTextField2.setText("Promocion 20%");
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 766, 370, 70));

        jTextField3.setBackground(new java.awt.Color(102, 102, 255));
        jTextField3.setText("Precio Total");
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 876, 250, 90));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Confirmar Viaje");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 920, 100, 50));

        jTextField4.setBackground(new java.awt.Color(102, 102, 255));
        jTextField4.setText("Precio");
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1285, 436, 130, 70));

        jTextField5.setBackground(new java.awt.Color(102, 102, 255));
        jTextField5.setText("Precio");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 546, 130, 70));

        jTextField6.setBackground(new java.awt.Color(102, 102, 255));
        jTextField6.setText("Precio");
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 656, 130, 70));

        jTextField7.setBackground(new java.awt.Color(102, 102, 255));
        jTextField7.setText("Precio");
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 2, true));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 756, 130, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/FondoPlanificarViaje (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 987, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        cargarPrecioDestino();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // ── UI setup ──────────────────────────────────────────────────────────────

    private void configurarUI() {
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField3.setEditable(false);
        jTextField2.setEditable(false);

        jComboBox2.addActionListener(e -> actualizarPrecioHabitacion());
        jComboBox3.addActionListener(e -> actualizarPrecioHotel());

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().equals("Actividades")) jTextField1.setText("");
            }
            @Override public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().isEmpty()) jTextField1.setText("Actividades");
                actualizarPrecioActividades();
            }
        });

        jButton1.addActionListener(e -> confirmarViaje());
        jToggleButton1.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
    }

    // ── Precio destino (BD) ───────────────────────────────────────────────────

    private void cargarPrecioDestino() {
        String nombre = (String) jComboBox1.getSelectedItem();
        if (nombre == null) return;

        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(
                     "SELECT idDestino, precio_base FROM Destino WHERE nombre = ? LIMIT 1")) {
                ps.setString(1, nombre);
                try (java.sql.ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        int id      = rs.getInt("idDestino");
                        double base = rs.getDouble("precio_base");
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            idDestinoSeleccionado = id;
                            precioBase = base;
                            actualizarPrecioHotel();
                        });
                    } else {
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            idDestinoSeleccionado = -1;
                            precioBase = 0;
                            recalcularTotal();
                        });
                    }
                }
            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(this::recalcularTotal);
            }
        });
    }

    // ── Precios locales ───────────────────────────────────────────────────────

    private void actualizarPrecioHotel() {
        String cat = (String) jComboBox3.getSelectedItem();
        precioHotel = (cat != null && cat.equals("5 Estrellas")) ? 500 : 150;
        jTextField4.setText(String.format("%.0f €", precioBase + precioHotel));
        actualizarPrecioHabitacion();
    }

    private void actualizarPrecioHabitacion() {
        String tipo = (String) jComboBox2.getSelectedItem();
        if (tipo == null) tipo = "";
        switch (tipo) {
            case "Cama Doble":  precioHabitacion = 150; break;
            case "Cama Balcon": precioHabitacion = 350; break;
            default:            precioHabitacion = 100; break;
        }
        jTextField5.setText(String.format("%.0f €", precioHabitacion));
        actualizarPrecioActividades();
    }

    private void actualizarPrecioActividades() {
        String texto = jTextField1.getText().trim();
        precioActividades = (!texto.isEmpty() && !texto.equals("Actividades")) ? 200 : 0;
        jTextField6.setText(String.format("%.0f €", precioActividades));
        recalcularTotal();
    }

    private void recalcularTotal() {
        double subtotal  = precioBase + precioHotel + precioHabitacion + precioActividades;
        double descuento = subtotal * 0.20;
        double total     = subtotal - descuento;
        jTextField7.setText(String.format("-%.0f €", descuento));
        jTextField3.setText(String.format("%.0f €", total));
    }

    // ── Confirmar viaje ───────────────────────────────────────────────────────

    private static final String[] PILOTOS = {
        "Capitán García", "Capitán Martínez", "Capitán López",
        "Capitán Rodríguez", "Capitán Fernández", "Capitán Torres"
    };
    private static final String[] AVIONES = {
        "Boeing 737", "Airbus A320", "Boeing 787 Dreamliner",
        "Airbus A380", "Boeing 777", "Airbus A350"
    };
    private static final String[] HOTELES_4 = {
        "Hotel Belveder", "Hotel Continental", "Hotel Meridian", "Hotel Palacio"
    };
    private static final String[] HOTELES_5 = {
        "Grand Hotel Royal", "Hotel Luxe Palace", "The Prestige Hotel", "Hotel Imperial"
    };

    private void confirmarViaje() {
        if (idDestinoSeleccionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El destino seleccionado no está disponible en la base de datos.",
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        double total;
        try {
            total = Double.parseDouble(jTextField3.getText().replace(" €", ""));
        } catch (NumberFormatException ex) {
            total = 0;
        }

        java.util.Random rnd = new java.util.Random();
        final double precioFinal   = total;
        final int    idDestino     = idDestinoSeleccionado;
        final String nombreDestino = (String) jComboBox1.getSelectedItem();
        final String catHotel      = (String) jComboBox3.getSelectedItem();
        final int    estrellas     = (catHotel != null && catHotel.equals("5 Estrellas")) ? 5 : 4;
        final String nombreHotel   = estrellas == 5
                ? HOTELES_5[rnd.nextInt(HOTELES_5.length)]
                : HOTELES_4[rnd.nextInt(HOTELES_4.length)];
        final String piloto        = PILOTOS[rnd.nextInt(PILOTOS.length)];
        final String avion         = AVIONES[rnd.nextInt(AVIONES.length)];
        final String numVuelo      = String.format("SR-%04d", rnd.nextInt(9000) + 1000);
        String actText = jTextField1.getText().trim();
        final String actividades   = (actText.isEmpty() || actText.equals("Actividades")) ? null : actText;

        jButton1.setEnabled(false);

        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion()) {
                con.setAutoCommit(false);

                // 1. Insertar Viaje
                int idViaje;
                try (java.sql.PreparedStatement ps = con.prepareStatement(
                     "INSERT INTO Viaje (fecha_inicio, fecha_fin, precio_total, Id_Destino, Id_Cliente) " +
                     "VALUES (CURDATE(), DATE_ADD(CURDATE(), INTERVAL 7 DAY), ?, ?, ?)",
                     java.sql.Statement.RETURN_GENERATED_KEYS)) {
                    ps.setDouble(1, precioFinal);
                    ps.setInt(2, idDestino);
                    ps.setInt(3, idCliente);
                    ps.executeUpdate();
                    try (java.sql.ResultSet rs = ps.getGeneratedKeys()) {
                        rs.next();
                        idViaje = rs.getInt(1);
                    }
                }

                // 1b. Insertar actividades en Viaje_has_Actividad
                if (actividades != null) {
                    for (String nom : actividades.split(",")) {
                        String nomAct = nom.trim();
                        if (nomAct.isEmpty()) continue;
                        int idActividad, idActDestino;
                        try (java.sql.PreparedStatement ps = con.prepareStatement(
                             "SELECT idActividad, Id_Destino FROM Actividad WHERE nombre = ? AND Id_Destino = ? LIMIT 1")) {
                            ps.setString(1, nomAct);
                            ps.setInt(2, idDestino);
                            try (java.sql.ResultSet rs = ps.executeQuery()) {
                                if (rs.next()) {
                                    idActividad  = rs.getInt("idActividad");
                                    idActDestino = rs.getInt("Id_Destino");
                                } else {
                                    try (java.sql.PreparedStatement psI = con.prepareStatement(
                                         "INSERT INTO Actividad (nombre, descripcion, precio, Id_Destino) VALUES (?, '', 0, ?)",
                                         java.sql.Statement.RETURN_GENERATED_KEYS)) {
                                        psI.setString(1, nomAct);
                                        psI.setInt(2, idDestino);
                                        psI.executeUpdate();
                                        try (java.sql.ResultSet rsI = psI.getGeneratedKeys()) {
                                            rsI.next();
                                            idActividad  = rsI.getInt(1);
                                            idActDestino = idDestino;
                                        }
                                    }
                                }
                            }
                        }
                        try (java.sql.PreparedStatement ps = con.prepareStatement(
                             "INSERT INTO Viaje_has_Actividad (Viaje_idViaje, Viaje_Id_Destino, Viaje_Id_Cliente, " +
                             "Actividad_idActividad, Actividad_Id_Destino) VALUES (?, ?, ?, ?, ?)")) {
                            ps.setInt(1, idViaje);
                            ps.setInt(2, idDestino);
                            ps.setInt(3, idCliente);
                            ps.setInt(4, idActividad);
                            ps.setInt(5, idActDestino);
                            ps.executeUpdate();
                        }
                    }
                }

                // 2. Insertar Reserva
                try (java.sql.PreparedStatement ps = con.prepareStatement(
                     "INSERT INTO Reserva (Fecha_Reserva, estado, num_personas, precio_total, " +
                     "Cliente_idCliente, Viaje_idViaje, Viaje_Id_Destino, Viaje_Id_Cliente) " +
                     "VALUES (NOW(), 'Pendiente', 1, ?, ?, ?, ?, ?)")) {
                    ps.setDouble(1, precioFinal);
                    ps.setInt(2, idCliente);
                    ps.setInt(3, idViaje);
                    ps.setInt(4, idDestino);
                    ps.setInt(5, idCliente);
                    ps.executeUpdate();
                }

                // 3. Insertar Hotel con las estrellas seleccionadas
                try (java.sql.PreparedStatement ps = con.prepareStatement(
                     "INSERT INTO Hotel (nombre, direccion, categoria, Id_Destino) VALUES (?, ?, ?, ?)")) {
                    ps.setString(1, nombreHotel);
                    ps.setString(2, "Av. Principal, " + nombreDestino);
                    ps.setInt(3, estrellas);
                    ps.setInt(4, idDestino);
                    ps.executeUpdate();
                }

                // 4. Insertar Transporte (piloto + modelo avión)
                int idTransporte;
                try (java.sql.PreparedStatement ps = con.prepareStatement(
                     "INSERT INTO Transporte (tipo, Empresa, Origen, Destino, Fecha_salida, Fecha_llegada, " +
                     "Precio, Viaje_idViaje, Viaje_Id_Destino, Viaje_Id_Cliente) " +
                     "VALUES (?, ?, 'España', ?, NOW(), DATE_ADD(NOW(), INTERVAL 12 HOUR), 0, ?, ?, ?)",
                     java.sql.Statement.RETURN_GENERATED_KEYS)) {
                    ps.setString(1, avion);
                    ps.setString(2, piloto);
                    ps.setString(3, nombreDestino);
                    ps.setInt(4, idViaje);
                    ps.setInt(5, idDestino);
                    ps.setInt(6, idCliente);
                    ps.executeUpdate();
                    try (java.sql.ResultSet rs = ps.getGeneratedKeys()) {
                        rs.next();
                        idTransporte = rs.getInt(1);
                    }
                }

                // 5. Insertar Vuelo
                try (java.sql.PreparedStatement ps = con.prepareStatement(
                     "INSERT INTO Vuelo (Aerolinea, Numero_vuelo, Transporte_id_Transporte, " +
                     "Transporte_Viaje_idViaje, Transporte_Viaje_Id_Destino, Transporte_Viaje_Id_Cliente) " +
                     "VALUES ('SkyRoute Airlines', ?, ?, ?, ?, ?)")) {
                    ps.setString(1, numVuelo);
                    ps.setInt(2, idTransporte);
                    ps.setInt(3, idViaje);
                    ps.setInt(4, idDestino);
                    ps.setInt(5, idCliente);
                    ps.executeUpdate();
                }

                con.commit();

                javax.swing.SwingUtilities.invokeLater(() -> {
                    jButton1.setEnabled(true);
                    javax.swing.JOptionPane.showMessageDialog(this,
                        String.format("¡Viaje confirmado!%n%nHotel: %s (%d★)%nPiloto: %s%nAvión: %s%nVuelo: %s",
                            nombreHotel, estrellas, piloto, avion, numVuelo),
                        "Reserva confirmada",
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    new PantallaPrincipal(idCliente).setVisible(true);
                    dispose();
                });

            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jButton1.setEnabled(true);
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al confirmar el viaje:\n" + ex.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                });
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPlanificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPlanificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPlanificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPlanificarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPlanificarViaje(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
