/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agencia_viajes;

/**
 *
 * @author Usuario
 */
public class VisualizarViaje extends javax.swing.JFrame {

    private int idCliente;

    public VisualizarViaje(int idCliente) {
        this.idCliente = idCliente;
        initComponents();
        configurarUI();
        cargarUltimoViaje();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(51, 51, 255));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 590, 20));

        jTextField2.setBackground(new java.awt.Color(51, 51, 255));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 590, -1));

        jTextField3.setBackground(new java.awt.Color(51, 51, 255));
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 590, -1));

        jTextField4.setBackground(new java.awt.Color(51, 51, 255));
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 590, -1));

        jTextField5.setBackground(new java.awt.Color(51, 51, 255));
        jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 590, -1));

        jTextField6.setBackground(new java.awt.Color(51, 51, 255));
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 590, -1));

        jTextField7.setBackground(new java.awt.Color(51, 51, 255));
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, 590, -1));

        jTextField8.setBackground(new java.awt.Color(51, 51, 255));
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 690, 590, -1));

        jTextField9.setBackground(new java.awt.Color(51, 51, 255));
        jTextField9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 2, true));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 740, 310, 50));

        jTextField10.setText("NombreUsuario");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/reserva_vuelo_1920x1080.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 827, 600, 70));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 1017, 40, 40));

        jToggleButton2.setText("jToggleButton2");
        getContentPane().add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 1017, 30, 40));

        jToggleButton3.setText("jToggleButton3");
        getContentPane().add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void configurarUI() {
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField9.setEditable(false);
        jTextField10.setEditable(false);

        jButton1.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
        jToggleButton1.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
        jToggleButton2.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
        jToggleButton3.addActionListener(e -> {
            new PantallaPrincipal(idCliente).setVisible(true);
            dispose();
        });
    }

    private void cargarUltimoViaje() {
        ConexionDB.getExecutor().submit(() -> {
            String sql =
                "SELECT c.nomCliente, c.apCliente, d.nombre AS destino, v.fecha_inicio, " +
                "       v.precio_total, h.categoria AS estrellas, " +
                "       t.Empresa AS piloto, t.tipo AS avion, " +
                "       (SELECT GROUP_CONCAT(a.nombre SEPARATOR ', ') " +
                "          FROM Viaje_has_Actividad vha " +
                "          JOIN Actividad a ON vha.Actividad_idActividad = a.idActividad " +
                "                         AND vha.Actividad_Id_Destino = a.Id_Destino " +
                "         WHERE vha.Viaje_idViaje = v.idViaje " +
                "           AND vha.Viaje_Id_Destino = v.Id_Destino " +
                "           AND vha.Viaje_Id_Cliente = v.Id_Cliente) AS actividades " +
                "FROM Viaje v " +
                "JOIN Cliente     c  ON v.Id_Cliente       = c.idCliente " +
                "JOIN Destino     d  ON v.Id_Destino       = d.idDestino " +
                "LEFT JOIN Transporte t  ON t.Viaje_idViaje    = v.idViaje " +
                "                      AND t.Viaje_Id_Destino  = v.Id_Destino " +
                "                      AND t.Viaje_Id_Cliente  = v.Id_Cliente " +
                "LEFT JOIN Hotel      h  ON h.Id_Destino = v.Id_Destino " +
                "WHERE v.Id_Cliente = ? " +
                "ORDER BY v.idViaje DESC LIMIT 1";

            String sqlPromo =
                "SELECT codigo, descuento FROM Promociones " +
                "WHERE fecha_fin >= CURDATE() ORDER BY descuento DESC LIMIT 1";

            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setInt(1, idCliente);
                try (java.sql.ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        String nombre    = rs.getString("nomCliente");
                        String apellido  = rs.getString("apCliente");
                        String destino   = rs.getString("destino");
                        String fecha     = rs.getString("fecha_inicio");
                        String precio      = rs.getString("precio_total");
                        String actividades = rs.getString("actividades");
                        int    estrellas   = rs.getInt("estrellas");
                        String piloto      = rs.getString("piloto");
                        String avion       = rs.getString("avion");

                        String promoTexto;
                        try (java.sql.PreparedStatement psP = con.prepareStatement(sqlPromo);
                             java.sql.ResultSet rsP = psP.executeQuery()) {
                            promoTexto = rsP.next()
                                ? rsP.getString("codigo") + " — " + rsP.getDouble("descuento") + "% dto."
                                : "Sin promociones activas";
                        }

                        final String promo = promoTexto;
                        final String actividadesFinal = actividades;
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            jTextField1.setText(destino  != null ? destino : "");
                            jTextField2.setText((nombre  != null ? nombre  : "") + " " +
                                                (apellido!= null ? apellido: ""));
                            jTextField3.setText(fecha    != null ? fecha   : "");
                            jTextField4.setText(actividadesFinal != null ? actividadesFinal : "No especificadas");
                            jTextField5.setText(estrellas + " estrellas");
                            jTextField6.setText(promo);
                            jTextField7.setText(avion    != null ? avion   : "");
                            jTextField8.setText(piloto   != null ? piloto  : "");
                            jTextField9.setText(precio   != null ? precio + " €" : "");
                        });
                    } else {
                        javax.swing.SwingUtilities.invokeLater(() ->
                            jTextField1.setText("No hay viajes registrados"));
                    }
                }
            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() ->
                    jTextField1.setText("Error al cargar datos"));
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarViaje(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
