/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agencia_viajes;

/**
 *
 * @author Usuario
 */
public class PantallaIncio extends javax.swing.JFrame {

    /**
     * Creates new form PantallaIncio
     */
    private int idClienteActual = -1;

    public PantallaIncio() {
        initComponents();
        configurarPlaceholders();
        configurarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 243, 241));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(222, 229, 227), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setBackground(new java.awt.Color(0, 153, 153));
        jToggleButton1.setForeground(new java.awt.Color(204, 204, 255));
        jToggleButton1.setText("Iniciar Sesion");
        jToggleButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 255), 2, true));
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 120, 30));

        jToggleButton2.setBackground(new java.awt.Color(0, 153, 153));
        jToggleButton2.setForeground(new java.awt.Color(204, 204, 255));
        jToggleButton2.setText("Crea tu cuenta");
        jToggleButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(206, 206, 255), 2, true));
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 120, 40));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 183, 183));
        jLabel1.setText("Tu proxima aventura te esta esperando");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("SkyRouteJoruney");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jTextField1.setBackground(new java.awt.Color(217, 224, 223));
        jTextField1.setForeground(new java.awt.Color(186, 181, 181));
        jTextField1.setText("Correo electronico");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 210, 30));

        jTextField2.setBackground(new java.awt.Color(217, 226, 225));
        jTextField2.setForeground(new java.awt.Color(187, 183, 183));
        jTextField2.setText("Contrseña");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 210, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("¿No tienes una cuenta?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 370, 320));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(207, 230, 255), 3, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 450, 400));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ElementosGraficos/PaisesIconos/fondo_960x540.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarPlaceholders() {
        java.awt.Color colorPlaceholder = new java.awt.Color(186, 181, 181);
        java.awt.Color colorTexto = new java.awt.Color(40, 40, 40);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().equals("Correo electronico")) {
                    jTextField1.setText("");
                    jTextField1.setForeground(colorTexto);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField1.getText().isEmpty()) {
                    jTextField1.setText("Correo electronico");
                    jTextField1.setForeground(colorPlaceholder);
                }
            }
        });

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (jTextField2.getText().equals("Contrseña")) {
                    jTextField2.setText("");
                    jTextField2.setForeground(colorTexto);
                }
            }
            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (jTextField2.getText().isEmpty()) {
                    jTextField2.setText("Contrseña");
                    jTextField2.setForeground(colorPlaceholder);
                }
            }
        });
    }

    private void configurarBotones() {
        jToggleButton1.addActionListener(e -> iniciarSesion());
        jToggleButton2.addActionListener(e -> {
            new PantallaRegistro().setVisible(true);
            jToggleButton2.setSelected(false);
        });
        // jButton1 no existe en este form — el minijuego se abre desde PantallaPrincipal
    }

    private void iniciarSesion() {
        String correo    = jTextField1.getText().trim();
        String contrasena = jTextField2.getText().trim();

        boolean correoVacio    = correo.isEmpty()    || correo.equals("Correo electronico");
        boolean contrasenaVacia = contrasena.isEmpty() || contrasena.equals("Contrseña");

        if (correoVacio || contrasenaVacia) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Por favor ingresa tu correo y contraseña.",
                "Campos vacíos",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            jToggleButton1.setSelected(false);
            return;
        }

        // Deshabilitar el botón mientras se consulta la BD
        jToggleButton1.setEnabled(false);
        jToggleButton1.setText("Verificando...");

        // Ejecutar en el pool de hilos para no bloquear la interfaz
        ConexionDB.getExecutor().submit(() -> {
            try (java.sql.Connection con = ConexionDB.getConexion();
                 java.sql.CallableStatement cs = con.prepareCall("{CALL sp_login_cliente(?, ?, ?, ?, ?)}")) {

                // Parámetros de entrada
                cs.setString(1, correo);
                cs.setString(2, contrasena);

                // Parámetros de salida
                cs.registerOutParameter(3, java.sql.Types.INTEGER); // resultado (1=ok, 0=error)
                cs.registerOutParameter(4, java.sql.Types.INTEGER); // idCliente
                cs.registerOutParameter(5, java.sql.Types.VARCHAR); // nombre

                cs.execute();

                int    resultado = cs.getInt(3);
                int    idCliente = cs.getInt(4);
                String nombre    = cs.getString(5);

                // Volver al EDT de Swing para actualizar la interfaz
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jToggleButton1.setEnabled(true);
                    jToggleButton1.setText("Iniciar Sesion");

                    if (resultado == 1) {
                        idClienteActual = idCliente;
                        new PantallaPrincipal(idCliente).setVisible(true);
                        dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(this,
                            "Correo o contraseña incorrectos.",
                            "Error de inicio de sesión",
                            javax.swing.JOptionPane.ERROR_MESSAGE);
                        jToggleButton1.setSelected(false);
                    }
                });

            } catch (java.sql.SQLException ex) {
                javax.swing.SwingUtilities.invokeLater(() -> {
                    jToggleButton1.setEnabled(true);
                    jToggleButton1.setText("Iniciar Sesion");
                    javax.swing.JOptionPane.showMessageDialog(this,
                        "No se pudo conectar con la base de datos:\n" + ex.getMessage(),
                        "Error de conexión",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                    jToggleButton1.setSelected(false);
                });
            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaIncio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaIncio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
